server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600


eureka:
  client:
    defaultZone: //localhost:8761/eureka/
token:
  secret: 2829dfcaad161b7a5510bee4891df572345fd5b1699ee5f52a7dc62f2889b0bd
#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "https://docs.spring.io"
#            allowedMethods:
#              - GET
#
#  .port=8082
#spring.application.name=api-gateway
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#spring.cloud.gateway.discovery.locator.enabled=true
#token.secret=2829dfcaad161b7a5510bee4891df572345fd5b1699ee5f52a7dc62f2889b0bd